prog_dilleri = ["C", "C++", "C#", "Java"]
dersler = ["Makine Ogrenmesi", "Ag Guvenligi", "Mikro", "Gomulu"]
sehirler = ["Bolu", "Eskisehir", "Ankara", "Sakarya"]
devre_elemanlari = ["direnc", "diyot", "transistor", "LED"]
prog_dilleri[0] = "Ruby"
dersler[1] = "Devre Teorisi"
sehirler[2] = "Istanbul"
devre_elemanlari[3] = "Potansiyometre"
prog_dilleri = dersler
prog_dilleri[2] = "Kotlin"
dersler[0] = "Bitirme Calismasi"
dersler[3] = "İsaret ve Sistemler"
print(*prog_dilleri, sep="\n")
sehirler = devre_elemanlari
devre_elemanlari = prog_dilleri
prog_dilleri[0] = "Go"
dersler[1] = "Tasarim Calismasi"
devre_elemanlari[2] = "Kondansator"
print(*dersler, sep="\n")
print(*sehirler, sep="\n")